version: 2
updates:
  - package-ecosystem: "maven" # Or "pip", "maven", etc.
    directory: "/"           # Directory containing the dependency file
    schedule:
      interval: "weekly"      # Frequency of updates
